before_install: 
  - sudo apt-get install libicu-dev -y
  # Short-term fix addressing https://github.com/bundler/bundler/issues/2784
  - gem update --system 2.1.11
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
notifications:
  disabled: true
