language: ruby
sudo: false
addons:
  apt:
    packages:
    - libicu-dev
    - libicu48
before_install: script/travis/before_install
rvm:
  - 2.0.0
  - 2.1
  - 2.2
notifications:
  disabled: true
git:
  submodules: false
cache: bundler
