name: Run Tests

on: [push, pull_request]

jobs:
  run:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', '2.5.x', '2.4.x', '2.3.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: script/ci/install_deps
    - name: Run tests
      run: |
        git checkout c20ebee0ebf33f73313d4694680521f80635d477
        ls -lR test/fixtures/
        bundle exec bin/github-linguist --breakdown
        git checkout $GITHUB_REF
        bundle exec rake
      env:
        LC_ALL: C.UTF-8
    - name: Check Licenses
      run: script/licensed status
